name: 🚀 Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea to improve our Helm charts.
        Please fill in as much of the following form as you're able.
  - type: input
    attributes:
      label: Name and Version
      description: Chart name and optional version
      placeholder: mariadb 0.1.5
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the problem this feature will solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like?
      description: A clear and concise description of what you want to happen. PRs are welcome.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered?
  - type: textarea
    attributes:
      label: Additional informations
      description: Tell us anything else you think we should know.
  - type: markdown
    attributes:
      value: |
        Select helm charts if your idea applies to them, so we can auto-label your issue.
  - type: dropdown
    attributes:
      label: Affected Helm charts
      description: Select one or more (optional)
      multiple: true
      options:
        - universal
        - clusterpirate
        - common
        - keycloak
        - mariadb
        - memcached
        - minio
        - mongodb
        - nginx
        - postgres
        - rabbitmq
        - redis
        - timescaledb
        - valkey
